services:
    final_exam-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: final_exam-app
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        environment:
            APP_ENV: prod
            DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@final_exam-db:3306/${MYSQL_DATABASE}?serverVersion=8.0.32&charset=utf8mb4
        depends_on:
            - final_exam-db
        networks:
            - mifania_platform-network

volumes:
    mysql_data:

networks:
    mifania_platform-network:
